### ISSUE TITLE
Cannot read properties of undefined (reading 'pathname')

### ISSUE THREAD

**Issue by DeathRight** [egoist/vite-plugin-mix#25]
Hey, I just started using this plugin on a new project, but I immediately got an error, shown below.
The repo is here (dev branch): https://github.com/DeathRight/tavernchat/tree/dev
```
C:\Users\onlyd\Documents\GitHub\tavernchat\node_modules\.pnpm\vite@2.7.13\node_modules\vite\dist\node\chunks\dep-f5552faa.js:40166
    var path = parseUrl(req).pathname || '/';
                            ^

TypeError: Cannot read properties of undefined (reading 'pathname')
    at next (C:\Users\onlyd\Documents\GitHub\tavernchat\node_modules\.pnpm\vite@2.7.13\node_modules\vite\dist\node\chunks\dep-f5552faa.js:40166:29)
    at C:\Users\onlyd\Documents\GitHub\tavernchat\node_modules\.pnpm\vite-plugin-mix@0.3.1_vite@2.7.13\node_modules\vite-plugin-mix\dist\index.js:931:11
```

I get this when I run `dev`. Seems to be entirely an issue with Vite and/or this plugin. Any help would be appreciated!
(Without this plugin, it runs fine.)

**Comment by stubar** [comment]
I'm also seeing this with Express.  Is seems to be when I use it with '@vitejs/plugin-basic-ssl'.   If I turn SSL off it's fine.
