### ISSUE TITLE
Support for Vite 4

### ISSUE THREAD

**Issue by TheJaredWilcurt** [egoist/vite-plugin-mix#42]
You can't `npm install` it if using Vite 4 (without `--force`, which obviously isn't ideal).

Fixed by #43

**Comment by srguiwiz** [comment]
I seems to be working for me with `npm install --force` when having Vite 4.0.4.  Does anyone know a specific reason not to update the dependency?

Should in file `vite-plugin-mix/package.json` section `devDependencies` change to say
```
"vite": "^3.1.8 || ^4.0.4",`
```
and `peerDependencies` change to
```
"vite": "^3 || ^4"
```
?

**Comment by borjalan** [comment]
Same here. Working fine on vite 4.0.0

**Comment by srguiwiz** [comment]
A fix in pull request #43 may need approval by @egoist .

**Comment by srguiwiz** [comment]
Does anyone know a reason not to merge pull request #43 to fix this issue?

Would be nice to use again from npm.

**Comment by SilverSeva** [comment]
Dude, please fix this.

**Comment by arrigod** [comment]
I would also need this. Is this going to be fixed?

**Comment by DenisTimofijuk** [comment]
"vite": "^4.1.0"

```
$ npm i vite-plugin-mix -D
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree     
npm ERR!
npm ERR! While resolving: chat_app@0.0.0
npm ERR! Found: vite@4.1.4
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.1.0" from the root project      
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3" from vite-plugin-mix@0.4.0      
npm ERR! node_modules/vite-plugin-mix
npm ERR!   dev vite-plugin-mix@"*" from the root projectnpm ERR!
npm ERR! Fix the upstream dependency conflict, or retry 
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

**Comment by DenisTimofijuk** [comment]
This is not working at all. Did everything as per instructions - got bunch of errors.
```

$ npm i vite-plugin-mix -D --force
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: vite-plugin-mix@0.4.0
npm WARN Found: vite@4.1.4
npm WARN node_modules/vite
npm WARN   dev vite@"^4.1.0" from the root project      
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer vite@"^3" from vite-plugin-mix@0.4.0      
npm WARN node_modules/vite-plugin-mix
npm WARN   dev vite-plugin-mix@"*" from the root projectnpm WARN
npm WARN Conflicting peer dependency: vite@3.2.5        
npm WARN node_modules/vite
npm WARN   peer vite@"^3" from vite-plugin-mix@0.4.0    
npm WARN   node_modules/vite-plugin-mix
npm WARN     dev vite-plugin-mix@"*" from the root project
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade 
to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

added 86 packages, and audited 102 packages in 11s      

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


$ npm run dev

> chat_app@0.0.0 dev
> vite

failed to load config from E:\Projects\chat_app\vite.config.ts
error when starting dev server:
TypeError: mix is not a function
    at file:///E:/Projects/chat_app/vite.config.ts.timestamp-1677780730317.mjs:6:5
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async loadConfigFromBundledFile (file:///E:/Projects/chat_app/node_modules/vite/dist/node/chunks/dep-ca21228b.js:62337:21)
    at async loadConfigFromFile (file:///E:/Projects/chat_app/node_modules/vite/dist/node/chunks/dep-ca21228b.js:62222:28)
    at async resolveConfig (file:///E:/Projects/chat_app/node_modules/vite/dist/node/chunks/dep-ca21228b.js:61843:28)
    at async createServer (file:///E:/Projects/chat_app/node_modules/vite/dist/node/chunks/dep-ca21228b.js:61153:20)
    at async CAC.<anonymous> (file:///E:/Projects/chat_app/node_modules/vite/dist/node/cli.js:734:24)   

```

**Comment by srguiwiz** [comment]
As a reasonable **workaround**, we found out it installs fine and works fine for a project since adding an `overrides` section to that project's `package.json`.

Here showing context for clarity:
```
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "vite": "^4.1.4",
    "vite-plugin-mix": "^0.4.0"
  },
  "overrides": {
    "vite-plugin-mix": {
      ".": "^0.4.0",
      "vite": "^4.1.4"
    }
  }
```
It may be required to make the version numbers in the `overrides` section to be **exactly the same** as in the dependencies section.

**Comment by jmevel** [comment]
Very first time I'm using Vite, I did `npm create vite@latest`, selected React + TypeScript then followed what the message said `cd vite-project` and `npm install` and got a similar error too

>npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vite-project@0.0.0
npm ERR! Found: @typescript-eslint/parser@undefined
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"^5.61.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.61.0
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   dev @typescript-eslint/eslint-plugin@"^5.61.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Not a great first user experience IMO

**Comment by dotmartin** [comment]
Any chance we could see support for Vite 5 as well?

**Comment by vivekkhyaal** [comment]
Still facing this issue in Vite 5 as well.
